### ISSUE TITLE
Where to put flash method

### ISSUE THREAD

**Issue by fox1t** [fastify/fastify-flash#1]
I was wondering if the best place to mount `reply.flash()` method was inisde a `preHandler`. My plan is to build a fastify-plugin that decorates reply method.

**Comment by mcollina** [comment]
it should be on the Reply

**Comment by fox1t** [comment]
Yea, my bad, I pressed "enter" without a description and it sent it with just a title. Sorry :)

**Comment by fox1t** [comment]
Btw, i just answered my self. I'll use https://www.fastify.io/docs/latest/Decorators/ ;)

**Comment by fox1t** [comment]
OK I just finished exploration, both of `connect-express` and all fastify's hooks and decorators. I have some questions:
1. `connect-flash` uses [express/session](https://github.com/expressjs/session) in order to enable flash messages. The only fastify's session plugin I found is https://github.com/SerayaEryn/fastify-session and it is not official. What are we gonna do? 
2. Do we need support for string formatting [format](https://nodejs.org/api/util.html#util_util_format_format_args), as on [line 66](https://github.com/jaredhanson/connect-flash/blob/master/lib/flash.js#L66)

**Comment by mcollina** [comment]
I would recommend use https://github.com/mcollina/fastify-secure-session. I need to migrate that to the org anyway. fastify-session might also be ok.
