### ISSUE TITLE
Flash object message

### ISSUE THREAD

**Issue by TraLeeee** [fastify/fastify-flash#104]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently, the req.flash() function accepts two arguments: `type: string` and `message: string[] | [ string[] ]`.

As i think, The `req.flash()` should accept object in second arguments and not only `string[] | [ string[] ]`

### Motivation

Let's take an example that we can return a flash message to view which contain some errors and messages.
Currently if we using view engine render, and on fail validation, its so hard to return errors and message to view with just `string[]`

### Example

So here's how we could you this in view.
```typescript
const errors = { [property: string]: string[] | object } = {
  name: ['Name is required.'],
  email: ['Email is required.', 'Email must be valid.'],
  password: ['Password is required.', 'Password must be at least 8 characters long.'],
  address: {
    street: ['Street is required.'],
    city: ['City is required.'],
    zipcode: ['Zipcode must be valid.']
  }
};
-------------------------------------------------------------
req.flash('flashErrors', errors);
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

Make sure to keep supporting the current pattern to avoid a breaking change
