### ISSUE TITLE
Importing the package fails for version 6.0.1

### ISSUE THREAD

**Issue by Atema** [fastify/fastify-flash#116]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.1.0

### Plugin version

6.0.1

### Node.js version

22.11.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

AlmaLinux 9.4

### Description

After upgrading to version 6.0.1, the package `@fastify/flash` cannot be imported.

In version 6.0.1, the package structure has changed as a result of including tests. The module files are now located in the `lib/src/` directory instead of `lib/`. However, `package.json`'s `main` field still points to `/lib`, making imports of the package fail with an error `ERR_MODULE_NOT_FOUND`.

**Comment by andokai** [comment]
I can confirm that changing `main` from `"./lib"` to `"./lib/src"` fixes the issue. Want a PR?

**Comment by mcollina** [comment]
Yes please, thanks!

**Comment by abishekpp** [comment]
> ### Prerequisites
> * [x]  I have written a descriptive issue title
> * [x]  I have searched existing issues to ensure the bug has not already been reported
> 
> ### Fastify version
> 5.1.0
> 
> ### Plugin version
> 6.0.1
> 
> ### Node.js version
> 22.11.0
> 
> ### Operating system
> Linux
> 
> ### Operating system version (i.e. 20.04, 11.3, 10)
> AlmaLinux 9.4
> 
> ### Description
> After upgrading to version 6.0.1, the package `@fastify/flash` cannot be imported.
> 
> In version 6.0.1, the package structure has changed as a result of including tests. The module files are now located in the `lib/src/` directory instead of `lib/`. However, `package.json`'s `main` field still points to `/lib`, making imports of the package fail with an error `ERR_MODULE_NOT_FOUND`.
> 
> ### Link to code that reproduces the bug
> _No response_
> 
> ### Expected Behavior
> _No response_

Yes i also got this same issue. please fix it
