### ISSUE TITLE
fastify not found, proceeding anyway

### ISSUE THREAD

**Issue by yaneony** [fastify/fastify-flash#63]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

latest

### Plugin version

latest

### Node.js version

latest

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Description

Trying to import fastify-flash with
```import flash from 'fastify-flash';```
but getting notification. Is this plugin compatible with ESM?

### Steps to Reproduce

Try to import with ```import flash from 'fastify-flash';```

**Comment by Eomm** [comment]
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

It seems a regression https://github.com/fastify/fastify-plugin/issues/101

**Comment by climba03003** [comment]
> 
> It seems a regression [fastify/fastify-plugin#101](https://github.com/fastify/fastify-plugin/issues/101)

Actually, no. The check should be moved to `fastify` itself. `fastify-plugin` do not have that part of code anymore.

**Comment by mcollina** [comment]
what version of fastify-flash are you using?

**Comment by yaneony** [comment]
So, here is an example. Following happens with fastify-plugin & fastify-autoload together. Was testing around, all plugins I use work flawlessly, but only fastify-flash gave this message.

**1. Install dependencies:**
```JS
npm install fastify fastify-plugin fastify-flash fastify-autoload @fastify/session fastify-cookie pino-pretty
```


**2. index.mjs**
```JS
import fastify from 'fastify';
import autoload from 'fastify-autoload';

const app = fastify();

app.register(autoload, {
  dir: 'plugins',
  dirNameRoutePrefix: false,
  forceESM: true
});

app.ready(async (err) => {
  if (err) throw err;
  app.listen(3000, '127.0.0.1');
});
```

**3. /plugins/session.mjs**
```JS
import fp from 'fastify-plugin';
import crypto from 'crypto';
import cookie from 'fastify-cookie';
import session from '@fastify/session';

async function init(app, options) {
  app.register(cookie);
  app.register(session, {
    cookieName: 'session',
    secret: crypto.randomBytes(16).toString('hex'),
    cookie: {
      secure: false,
      maxAge:  2592000000
    }
  });
}

export default fp(init, {
  name: 'session',
  dependencies: []
});
```

**4. /plugins/flash.mjs**
```JS
import fp from 'fastify-plugin';
import flash from 'fastify-flash';

async function init(app, options) {
  app.register(flash);
}

export default fp(init, {
  name: 'flash',
  dependencies: ['session']
});
```

**5. Run**
```JS
node index.mjs
```


You will see **"fastify not found, proceeding anyway"** message on start.

**Comment by darkgl0w** [comment]
[This PR](https://github.com/fastify/fastify-flash/pull/64) should fix this issue.

**Comment by climba03003** [comment]
The `package.json` of this repo is correct. The problem is that we forget to release a new version for this [`PR`](https://github.com/fastify/fastify-flash/commit/444c40f522cabfe2791240afe299179c7bec57aa).

**Comment by Eomm** [comment]
I have tried to publish a new version but I don't have the necessary grants https://www.npmjs.com/package/fastify-flash

cc @mcollina

**Comment by darkgl0w** [comment]
cc @fox1t

**Comment by yaneony** [comment]
Any news on update?!
